apiVersion: v1
kind: Service
metadata:
  name: odoo-shop
  namespace: odoo
  labels:
    app: odoo-shop
spec:
  ports:
    - port: 8069
  selector:
    app: odoo-shop
    tier: frontend
  type: NodePort